--- 

- hosts: local
  connection: local
  become: yes
  gather_facts: false

  vars:
    service_account_email: 435207003416-compute@developer.gserviceaccount.com
    credentials_file: files/campbigfalcon-3efb7a22f475.json
    project_id: campbigfalcon-179100
    machine_type: n1-standard-1
    image: centos-7
    instance_name: docker
    instance_count: 1

  tasks:
    - name: spawn instance
      gce:
        name: "{{ instance_name }}"
        num_instances: "{{ instance_count }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        tags: http-server,https-server
      register: gce

    - debug:
        msg: "{{ gce }}"

    - name: wait for ssh to come up
      wait_for:
        host: "{{ item.public_ip }}"
        delay: 30
        port: 22
        state: started
        timeout: 60
      with_items: "{{ gce.instance_data }}"

    - name: remove old host entry
      lineinfile:
        path: /home/vagrant/virtualpy/gcp/hosts
        state: absent
        regexp: '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'

    - name: add new instance public ip
      lineinfile:
        path: /home/vagrant/virtualpy/gcp/hosts
        insertafter: '^\[gcp\]'
        line: "{{ item.public_ip }}"
      with_items: "{{ gce.instance_data }}"

    - meta: refresh_inventory

