--- 

- hosts: local
  connection: local
  become: yes
  gather_facts: false

  vars:
    service_account_email: 435207003416-compute@developer.gserviceaccount.com
    credentials_file: files/campbigfalcon-3efb7a22f475.json
    project_id: campbigfalcon-179100
    machine_type: n1-standard-1
    image: centos-7
    instance_name: docker
    instance_count: 1

  tasks:
    - name: delete instance
      gce:
        name: "{{ instance_name }}"
        num_instances: "{{ instance_count }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        state: deleted
      register: gce
